server {
    listen 443 ssl;
    server_name app.chain.local;

    ssl_certificate /etc/nginx/ssl/server_only.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    location / {
        return 200 "CA BENH 08: FULL CERTIFICATE CHAIN HOP LE (TLS OK)!\n";
        add_header Content-Type text/plain;
    }
}
