services:
  web-server:
    build: .
    container_name: lab01-web-server
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:80"
    networks:
      lab-net:
        ipv4_address: 172.28.0.10

  client:
    image: alpine:latest
    container_name: lab01-client
    command: sleep infinity
    init: true
    networks:
      lab-net:
        ipv4_address: 172.28.0.20
    depends_on:
      - web-server

networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
