! ==============================================================================
! KEEPALIVED PRODUCTION CONFIGURATION - NODE-B (BACKUP)
! Path: /etc/keepalived/keepalived.conf
! ==============================================================================

global_defs {
    router_id NODE_B
    enable_script_security
    script_user root

    # PRODUCTION TUNING CHO GRATUITOUS ARP (GARP):
    garp_master_delay 1
    garp_master_repeat 3
    garp_master_refresh 60
    garp_master_refresh_repeat 2
}

vrrp_script chk_nginx {
    script "/etc/keepalived/check_nginx.sh"
    interval 2
    timeout 2
    weight -20
    fall 2
    rise 2
}

vrrp_instance VI_SERVER {
    state BACKUP
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1

    # Tùy chọn RFC 5798 Virtual MAC:
    # use_vmac

    authentication {
        auth_type PASS
        auth_pass 9pingHA1
    }

    virtual_ipaddress {
        172.28.52.100/24 dev eth0 label eth0:vip
    }

    track_script {
        chk_nginx
    }

    # Bắn GARP ngay khi nhận VIP
    notify_master "/usr/sbin/arping -U -c 5 -I eth0 172.28.52.100"
}
