system {
    root-authentication {
        encrypted-password "$6$lB5c6$Zeud8c6IhCTE6hnZxXBl3ZMZTC2hOx9pxxYUWTHKW1oC32SATWLMH2EXarxWS5k685qMggUfFur1lq.o4p4cg1"; ## SECRET-DATA
    }
    login {
        user demo {
            uid 2000;
            class super-user;
            authentication {
                encrypted-password "$6$m0ek3$xp17f3VsXJIqZTLyAAE2.7r9o.HlZotP7hX887gIQp.YA6OqNAem9RIhUItFKJ3Fca5Ztirc3VPtcdNL8ZlsM."; ## SECRET-DATA
            }
        }
    }
    services {
        netconf {
            ssh;
        }
        ssh {
            root-login allow;
        }
    }
}