FROM alpine:latest
# curl: test HTTPS tu phia client
# libfaketime: gia lap dong ho Client bi sai gio (Clock Skew) ma khong dung den dong ho that
RUN apk add --no-cache curl libfaketime
CMD ["sleep", "infinity"]
