services:
  node-a:
    build:
      context: ./node
      args:
        NODE_NAME: "NODE A (MASTER)"
        NODE_IP: "172.28.5.11"
    container_name: lab05-node-a
    hostname: node-a
    cap_add:
      - NET_ADMIN
    networks:
      lab-net:
        ipv4_address: 172.28.5.11

  node-b:
    build:
      context: ./node
      args:
        NODE_NAME: "NODE B (BACKUP)"
        NODE_IP: "172.28.5.12"
    container_name: lab05-node-b
    hostname: node-b
    cap_add:
      - NET_ADMIN
    networks:
      lab-net:
        ipv4_address: 172.28.5.12

  client:
    build: ./client
    container_name: lab05-client
    cap_add:
      - NET_ADMIN
    command: sleep infinity
    init: true
    networks:
      lab-net:
        ipv4_address: 172.28.5.20
    depends_on:
      - node-a
      - node-b

networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.5.0/24
