services:
  web-server:
    image: nginx:alpine
    container_name: lab06-web-server
    hostname: app.local
    networks:
      lab-net:
        ipv4_address: 172.28.6.10

  client:
    image: alpine:latest
    container_name: lab06-client
    cap_add:
      - NET_ADMIN
    command: sleep infinity
    init: true
    networks:
      lab-net:
        ipv4_address: 172.28.6.20
    depends_on:
      - web-server

networks:
  lab-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.6.0/24
